logging.level.org.springframework=debug
logging.level.reactor.netty.http.client=debug
logging.level.org.apache=trace

# To fix the following from WebClientTests.testZstd():
# org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144
spring.http.codecs.max-in-memory-size=-1
